_wandb:
    value:
        cli_version: 0.25.0
        e:
            e8ajyjzlhby6unsuu7nsrekdjyptd33p:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: kadai1/1-7/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "456939810816"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/kenshu/.venv/bin/python3
                git:
                    commit: 7bec7881a0c138ee7e71d2b22fb950a4046bd284
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/kenshu/kadai1/1-7/main.py
                python: CPython 3.13.12
                root: /Users/tomita/kenshu/kadai1/1-7
                startedAt: "2026-02-17T09:53:22.819780Z"
                writerId: e8ajyjzlhby6unsuu7nsrekdjyptd33p
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
