_wandb:
    value:
        cli_version: 0.25.0
        e:
            dwtasem1yz6a0bjq342rr2wqxb5nmz7s:
                codePath: kadai2/2-4/main.py
                codePathLocal: main.py
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/lab/kenshu/.venv/bin/python3
                git:
                    commit: 28a91c7dff3a6ec58df047b7749aba77347d62d9
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/lab/kenshu/kadai2/2-4/main.py
                python: CPython 3.13.12
                root: /Users/tomita/lab/kenshu/kadai2/2-4
                startedAt: "2026-02-24T11:12:31.466304Z"
                writerId: dwtasem1yz6a0bjq342rr2wqxb5nmz7s
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
