wandb:
  project_name: "daimon2"
  train_name: "2-5_epoc300"
  config:
    device: "cuda:0"
  
train_data:
  batch_size: 50
  epoch: 300
  
model:
  encoder:
    channels: [16, 32]
    # kernelは奇数の方がいい
    kernels:  [3, 3]
    strides:  [2, 2]
    paddings: [1, 1]
  decoder:
    channels: [32, 16, 1]
    # kernelは奇数の方がいい
    kernels:  [3, 3,3]
    strides:  [2, 2,2]
    paddings: [1, 1,1]
  # 特徴量をフラットにした際の次元
  latent_obs_dim: 16
  mlp:
   hidden_dim: 128
  #  0でないと情報が失われる
   layers: 0



optimizer:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-6

params:
    channels: [1]
    kernels: [3]
    strides: [2]
    paddings: [1]