_wandb:
    value:
        cli_version: 0.25.0
        e:
            9hfod708vvu8x53ko94ccji1g1zw6v5x:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: kadai1/1-9/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "465264152576"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/kenshu/.venv/bin/python3
                git:
                    commit: d40c3aa04a2f5354a61b222fae8765132cef8c62
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/kenshu/kadai1/1-9/main.py
                python: CPython 3.13.12
                root: /Users/tomita/kenshu/kadai1/1-9
                startedAt: "2026-02-18T13:24:20.730224Z"
                writerId: 9hfod708vvu8x53ko94ccji1g1zw6v5x
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
