_wandb:
    value:
        cli_version: 0.25.0
        e:
            v99bue2cj3xeli1zj6ctq6hzli04blft:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: kadai1/1-8/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "501509210112"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/lab/kenshu/.venv/bin/python3
                git:
                    commit: 3d5beedf1105fbbf96d8508bbc7b083338301dd0
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/lab/kenshu/kadai1/1-8/main.py
                python: CPython 3.13.12
                root: /Users/tomita/lab/kenshu/kadai1/1-8
                startedAt: "2026-02-24T04:04:55.766404Z"
                writerId: v99bue2cj3xeli1zj6ctq6hzli04blft
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
