_wandb:
    value:
        cli_version: 0.25.0
        e:
            sidj0b5lwmg932lall7ecvd6gb0erb8u:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: kadai1/1-7/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "473482096640"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/kenshu/.venv/bin/python3
                git:
                    commit: 7e2aea3c599f0910435dba5a461e98940b185b3b
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/kenshu/kadai1/1-7/main.py
                python: CPython 3.13.12
                root: /Users/tomita/kenshu/kadai1/1-7
                startedAt: "2026-02-20T14:39:29.512388Z"
                writerId: sidj0b5lwmg932lall7ecvd6gb0erb8u
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
