_wandb:
    value:
        cli_version: 0.25.0
        e:
            14lk8m9lsgmuk7thxqawmvpcfs91lf3w:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: kadai1/1-8/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "456924495872"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/kenshu/.venv/bin/python3
                git:
                    commit: f2bd5e79ada644e703747d6865a1b3b7f8cd2121
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/kenshu/kadai1/1-8/main.py
                python: CPython 3.13.12
                root: /Users/tomita/kenshu/kadai1/1-8
                startedAt: "2026-02-17T10:19:56.058053Z"
                writerId: 14lk8m9lsgmuk7thxqawmvpcfs91lf3w
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
