wandb:
  project_name: "daimon1"
  train_name: "dummy"
  config:
    device: "cuda:0"

gen_data:
  points_per_round: 100
  num_rounds: 5
  min: 0
  max: 2 # ここでは np.pi と書けないので π を除いています
  
train_data:
  input_timestep: 10
  split_ratio: [0.7, 0.2, 0.1]
  batch_size: 50
  epoch: 1000
  
model:
  hidden_dim: 10

optimizer:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-6
