_wandb:
    value:
        cli_version: 0.25.0
        e:
            vft7m6d0f38pz122lg6civgagu2fgmdl:
                codePath: kadai1/1-10/main.py
                codePathLocal: main.py
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/kenshu/.venv/bin/python3
                git:
                    commit: 0d215b7a2532a6ebe5419a4a5530b9b443c09ad0
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/kenshu/kadai1/1-10/main.py
                python: CPython 3.13.12
                root: /Users/tomita/kenshu/kadai1/1-10
                startedAt: "2026-02-19T01:00:11.670419Z"
                writerId: vft7m6d0f38pz122lg6civgagu2fgmdl
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
