_wandb:
    value:
        cli_version: 0.25.0
        e:
            3g0fsw4oybzruaovstjgzj2pmu5bq9cm:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: kadai1/1-10/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "478121742336"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/kenshu/.venv/bin/python3
                git:
                    commit: 8f64115d40d0e14ac1b89672f5b2aab0c8224043
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/kenshu/kadai1/1-10/main.py
                python: CPython 3.13.12
                root: /Users/tomita/kenshu/kadai1/1-10
                startedAt: "2026-02-22T11:24:46.419716Z"
                writerId: 3g0fsw4oybzruaovstjgzj2pmu5bq9cm
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
device:
    value: cuda:0
